### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by IlanKalendarov** [mobdk/compilecs#1]
Hey I tried to compile your cloneprocess project with compile.bat.

it gives me that error: "CloneProcess.il(14) : error : syntax error at token ',' in: .locals init (uint8[] V_0,"

![Untitled](https://user-images.githubusercontent.com/43996999/99904106-8967cb80-2cd1-11eb-8faa-44979a59136b.png)

![aa](https://user-images.githubusercontent.com/43996999/99904077-61786800-2cd1-11eb-92b6-306b29917b22.png)

**Comment by mobdk** [comment]
did you fix it ?

**Comment by IlanKalendarov** [comment]
Yes Thanks anyway
